name: CCommands
version: ${project.version}
main: Cortex.CCommands.CCommandsMain
api-version: 1.16
load: STARTUP
depend: [CPermsPaper]
authors: [CommanderCortex]
description: Simple Commands To make life more simple
website: https://github.com/CommanderCortex
